-- Flyway V1: Create schema for Tenisu

-- Countries
CREATE TABLE countries (
    code VARCHAR(3) PRIMARY KEY,
    picture VARCHAR(512)
);

-- Players (inclut les colonnes de PlayerData car PlayerData est @Embeddable)
CREATE TABLE players (
    id BIGINT PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    shortname VARCHAR(20) NOT NULL,
    sex VARCHAR(1) NOT NULL,
    country_code VARCHAR(3) NOT NULL,
    picture VARCHAR(512),
    rank INT NOT NULL,
    points INT NOT NULL,
    weight INT NOT NULL,
    height INT NOT NULL,
    age INT NOT NULL,
    CONSTRAINT fk_player_country FOREIGN KEY (country_code) REFERENCES countries(code)
);
CREATE INDEX idx_players_country ON players(country_code);
CREATE INDEX idx_players_name ON players(lastname, firstname);

-- Player last results (array of last 5 results)
CREATE TABLE player_last_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    position INT NOT NULL,
    result_value INT NOT NULL,
    CONSTRAINT fk_lastresults_player FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT uk_player_position UNIQUE (player_id, position),
    CONSTRAINT chk_position_range CHECK (position BETWEEN 0 AND 4),
    CONSTRAINT chk_result_value_binary CHECK (result_value IN (0,1))
);
CREATE INDEX idx_last_results_player ON player_last_results(player_id);
