-- Flyway V3: Alter players.id to become an identity column for auto-increment
-- Convert existing primary key column to identity (H2 syntax)
ALTER TABLE players ALTER COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
-- Restart sequence at max(id)+1 (seed data max=102)
ALTER TABLE players ALTER COLUMN id RESTART WITH 103;

